---
# tasks file for vector-role
- name: Get Vector distrib
  ansible.builtin.get_url:
    url: "https://yum.vector.dev/stable/vector-0/x86_64/vector-{{ vector_version }}.x86_64.rpm"
    dest: "./vector-{{ vector_version }}.rpm"
- name: Install Vector package
  become: true
  ansible.builtin.yum:
    disable_gpg_check: true
    name:
      - vector-{{ vector_version }}.rpm
- name: Write config using jinja2
  become: true
  ansible.builtin.template:
    src: templates/vector.j2
    dest: /etc/vector/vector.yaml
    mode: 0644
  notify: Start Vector service
- name: Flush handlers
  meta: flush_handlers
