---
# role_name_check: 1

dependency:
  enabled: false
  name: galaxy
driver:
  name: docker
  # name: delegated
platforms:
  # - name: instance
  # - name: fedora
  #   image: docker.io/pycontribs/fedora
  #   # pre_build_image: true
  #   privileged: true
  #   volume_mounts:
  #       - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
  #   command: "/usr/sbin/init"
  #   environment: { container: docker }
  # - name: centos8
  #   image: docker.io/pycontribs/centos:8
  #   prebuildimage: true
  #   tty: True
  #   systemd: true
  - name: ubuntu
    image: docker.io/pycontribs/ubuntu:latest
    prebuildimage: true
    tty: True
    systemd: true
  # - name: centos9
  #   image: quay.io/centos/centos:stream9
  #   prebuildimage: true
  #   tty: True
  #   systemd: true
  # - name: ubuntu
  #   image: docker.io/pycontribs/ubuntu:latest
  #   # pre_build_image: true
  #   privileged: true
  #   volume_mounts:
  #       - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
  #   command: "/usr/sbin/init"
  #   environment: { container: docker }
provisioner:
  name: ansible
  # inventory:
  #   links:
  #     hosts: inventory.ini
verifier:
  name: ansible
    # you might want to add your own variables here based on what provisioning
    # you are doing like:
    # image: quay.io/centos/centos:stream8
